name: Python CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with: 
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          mkdir -p test-results
          pytest --junitxml=test-results/results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/

      - name: Build project
        run: |
          mkdir -p build
          echo "This is a build output" > build/output.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: build-artifacts
          path: build/

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test result artifact
        uses: actions/download-artifact@v3
        with: 
          name: test-results
          path: downloaded-test-results/

      - name: Display downloaded test results
        run: cat downloaded-test-results/results.xml 

      - name: Display downloaded build artifacts
        run: cat build/output.txt
