name: Python Cl Pipeline

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with: 
          path: |
            ~/.cache/pip
            key: ${{runner.os}}-pip-${{hashFiles(requirements.txt'}}
            restore-keys: |
              ${{runner.os}}-pip-

          - name: Install dependencies
            run: |
              python -m pip install --update pip 
              pip install -r requrements.txt

          - name: run tests
            run: |
              mkdir -p test-results
              pytest--junitxml=test-result/result.xml

          - name: upload test results
            uses: actions/upload-artifact@v3
            with:
              name: test-results
              path: test-results/

          - name: build project
            run: |
              mkdir -p build
              echo "this is a build output">build/output.txt

          - name: upload build artifact
            uses: actions/upload-artifact@v3
            with: 
              name: build-artifacts
              path: build/

          download:
            runs-on: ubuntu-latest
            needs: build
            steps:
              - name: checkout code
                uses: action/checkout@v4

              - name: download test result artifact
                uses: actions/download-artifact@v3
                with: 
                  name: test-results
                  path: download-test-results/


              - name: display download test results
                run: cat download-test-results/results.xml 

              - name: display download build artifacts
                run: cat download-build-artifacts/output.txt
                
              
