on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      greeting: ${{ steps.hello.outputs.greeting }}
    steps:
      - name: Generate Greeting
        id: Hello
        run: echo "::set-output name=greeting::Hello, Umair!"
job2:
  runs-on: ubuntu-latest
  needs: job1
  steps: 
    - name: use greeting from job1
      run: echo "The greeting from job1 is ${{needs.job1.outputs.greeting}}"


